// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV-h0nLUdQ6Sn2UyRZYLf4krPKID1fcck',
    appId: '1:173930507464:web:754acddaec3a77b4c2c9fd',
    messagingSenderId: '173930507464',
    projectId: 'saveme-36f84',
    authDomain: 'saveme-36f84.firebaseapp.com',
    storageBucket: 'saveme-36f84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgoZay055FtW0NcSDylBTJfCeTCMg7rHU',
    appId: '1:173930507464:android:b95c019d312f6e10c2c9fd',
    messagingSenderId: '173930507464',
    projectId: 'saveme-36f84',
    storageBucket: 'saveme-36f84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpOPLpivJ-TBouvMliCi5VhnKqEfOfWT8',
    appId: '1:173930507464:ios:1a8a65e7677b5e31c2c9fd',
    messagingSenderId: '173930507464',
    projectId: 'saveme-36f84',
    storageBucket: 'saveme-36f84.appspot.com',
    iosBundleId: 'com.example.saveMeNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpOPLpivJ-TBouvMliCi5VhnKqEfOfWT8',
    appId: '1:173930507464:ios:1a8a65e7677b5e31c2c9fd',
    messagingSenderId: '173930507464',
    projectId: 'saveme-36f84',
    storageBucket: 'saveme-36f84.appspot.com',
    iosBundleId: 'com.example.saveMeNew',
  );
}
